[project]
name = "meltano-tap-dummyjson"
dynamic = [ "version" ]
description = "Singer tap for DummyJSON, built with the Meltano Singer SDK"
readme = "README.md"
authors = [{ name = "Meltano Team", email = "hello@meltano.com" }]
keywords = [
    "ELT",
    "DummyJSON",
]
classifiers = [
    "Intended Audience :: Developers",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
license = "Apache-2.0"
license-files = ["LICENSE"]
requires-python = ">=3.10"
dependencies = [
    "requests~=2.32.3",
    "requests-cache~=1.2.1",
    "singer-sdk",
    "typing-extensions>=4.5.0; python_version < '3.12'",
]
optional-dependencies.s3 = [
    "s3fs>=2025.9.0",
]

[project.scripts]
# CLI declaration
tap-dummyjson = 'tap_dummyjson.tap:TapDummyJSON.cli'

[dependency-groups]
dev = [
    "pytest>=8",
    "singer-sdk[testing]",
]

[tool.hatch.build.targets.wheel]
packages = ["tap_dummyjson"]

[tool.hatch.version]
fallback-version = "0.0.0"
source = "vcs"

[tool.mypy]
python_version = "3.12"
warn_unused_configs = true

[tool.uv.sources]
singer-sdk = { workspace = true }

[build-system]
requires = ["hatchling", "hatch-vcs"]
build-backend = "hatchling.build"
