preview = true
src = ["tap_dummyjson"]

[lint]
ignore = [
    "CPY",
    "D",
    "PLR2004", # magic-value-comparison
    "RUF012",  # mutable-class-default
]
select = ["ALL"]

[lint.flake8-annotations]
allow-star-arg-any = true

[lint.isort]
known-first-party = ["tap_dummyjson"]

[lint.pydocstyle]
convention = "google"
