version: 2

enable-beta-ecosystems: true

multi-ecosystem-groups:
  python:
    schedule:
      interval: weekly

updates:
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
      time: "12:00"
    labels: [Dependencies]
    groups:
      development-dependencies:
        dependency-type: development
      runtime-dependencies:
        dependency-type: production
    versioning-strategy: lockfile-only
    cooldown:
      default-days: 7
    multi-ecosystem-group: python
    patterns: ["*"]
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "12:00"
    labels: [Dependencies]
    groups:
      development-dependencies:
        dependency-type: development
      runtime-dependencies:
        dependency-type: production
    versioning-strategy: increase-if-necessary
    cooldown:
      default-days: 7
    multi-ecosystem-group: python
    patterns: ["*"]
  - package-ecosystem: pip
    directory: "/.github/workflows/resources"
    schedule:
      interval: weekly
      time: "12:00"
    labels: [Dependencies]
    groups:
      ci:
        patterns:
          - "*"
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels: [Dependencies]
    groups:
      actions:
        patterns:
          - "*"
    cooldown:
      default-days: 7
