name: Release

on:
  push:

permissions:
  contents: write  # Needed to upload artifacts to the release
  id-token: write  # Needed for OIDC PyPI publishing

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: {{ '${{ steps.baipp.outputs.package_version }}' }}
    steps:
    - uses: actions/checkout@v4
    - uses: hynek/build-and-inspect-python-package@v2
      id: baipp

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: [build]
    ## TODO: optionally provide the name of the environment for the trusted
    ## publisher on PyPI
    ## https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment
    # environment:
    #   name: pypi
    {%- if cookiecutter.variant != "None (Skip)" %}
    #   url: https://pypi.org/project/{{cookiecutter.variant}}-{{cookiecutter.target_id}}/{{ '${{ steps.baipp.outputs.package_version }}' }}
    {%- else %}
    #   url: https://pypi.org/project/{{cookiecutter.target_id}}/{{ '${{ steps.baipp.outputs.package_version }}' }}
    {%- endif %}
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - name: Upload wheel to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: {{ '${{secrets.GITHUB_TOKEN}}' }}
        file: dist/*.whl
        tag: {{ '${{github.ref}}' }}
        overwrite: true
        file_glob: true

    - name: Publish
      ## TODO: create a trusted publisher on PyPI
      ## https://docs.pypi.org/trusted-publishers/
      uses: pypa/gh-action-pypi-publish@v1.12.3
